fbo_membership/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("memberships.urls")),
    path("accounts/", include("users.urls")),
    # path("accounts/reset_password/", PasswordResetView.as_view(), name="password_reset"),   
    # path("accounts/reset_password_confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    # path("accounts/reset_password_done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    # path("accounts/reset_password_complete/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

memberships/urls.py
from django.urls import path
from .views.home import HomeView, PlanDetailView, PackageView
from .views.subscriptionPlanView import SubscriptionPlanView
from .views.subscriptionPlanOrder import SubscriptionPlanOrder
from .views.orderListView import OrderListView

app_name = "memberships"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("package/", PackageView.as_view(), name="packageView"),
    path("plans/<slug:slug>/", PlanDetailView.as_view(), name="plan_detail"),
    path("subscription/<slug:membershipPlanSlug>/<slug:packageSlug>/", SubscriptionPlanView.as_view(), name="subscription"),
    path("subscription/order/<slug:membershipPlanSlug>/<slug:packageSlug>/", SubscriptionPlanOrder.as_view(), name="subscription_order"),
    path("orders/", OrderListView.as_view(), name="order_list"),
]

users/urls.py
from django.urls import path
from .views.sign_in import SignInView
from .views.sign_up import SignUpView, ActivateView
from .views.sign_out import SignOutView, SignOutConfirmationView
from .views.profile import ProfileView
from .views.forgot_password import ForgotPasswordView, ResetPasswordView, ResetPasswordEmailDoneView

app_name = "users"

urlpatterns = [
    path("login/", SignInView.as_view(), name="sign_in"),
    path("sign_up/", SignUpView.as_view(), name="sign_up"),
    path('activate/<uidb64>/<token>/', ActivateView.as_view(), name='activate'),
    path("sign_out_confirmation/", SignOutConfirmationView.as_view(), name="sign_out_confirmation"),
    path("sign_out/", SignOutView.as_view(), name="sign_out"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("forgot_password/", ForgotPasswordView.as_view(), name="forgot_password"),
    path("reset_password/<uidb64>/<token>/", ResetPasswordView.as_view(), name="password_reset"),
    path("reset_password_done/", ResetPasswordEmailDoneView.as_view(), name="password_reset_done"),
]

templates/memberships_base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/datepicker.min.js"></script>
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'memberships/css/navbar.css' %}" />
  </head>

  <body class="h-screen">
    {% if messages %} {% for message in messages %}
    <div
      class="text-center pt-1 lg:px-4"
      style="
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        z-index: 1000;
        width: 100%;
      "
      id="message_alart"
    >
      <div
        class="p-2 bg-indigo-800 items-center text-indigo-100 leading-none lg:rounded-full flex lg:inline-flex"
        role="alert"
      >
        <span class="mr-2 p-1 text-left flex-auto"> {{ message | safe }} </span>
        <span class="top-0 bottom-0 right-0 px-3 py-0">
          <svg
            class="fill-current h-6 w-6 text-red-500"
            role="button"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20"
          >
            <title>Close</title>
            <path
              d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"
            />
          </svg>
        </span>
      </div>
    </div>
    {% endfor %} {% endif %}

    <header class="bg-gray-200">
      <nav class="flex justify-between items-center w-full md:px-32 pl-9">
        <div class="flex items-center gap-6">
          <ion-icon
            onclick="onToggleMenu(this)"
            name="menu"
            class="text-3xl cursor-pointer md:hidden"
          ></ion-icon>
          <div>
            <a href="{% url 'memberships:home' %}">
              <h3 class="text-3xl font-bold md:text-4xl">FBO</h3>
            </a>
          </div>
        </div>

        <div
          class="nav-links duration-500 md:static absolute md:min-h-fit md:h-1/2 h-60 md:bg-gray-200 bg-gray-100 left-0 top-[-100%] md:w-auto w-full flex items-center px-5 ease-in-out duration-700"
        >
          <ul
            class="flex md:flex-row flex-col md:items-center gap-2 font-bold w-full"
          >
            <li class="hover:bg-gray-200 block py-2 px-3 rounded-md">
              <a href="{% url 'memberships:home' %}">HOME</a>
            </li>
            <li class="hover:bg-gray-200 block py-2 px-3 rounded-md">
              <a href="{% url 'memberships:packageView' %}">PACKAGE</a>
            </li>
            <li class="hover:bg-gray-200 block py-2 px-3 rounded-md">
              <a href="#">SERVICE</a>
            </li>
            <li class="hover:bg-gray-200 block py-2 px-3 rounded-md">
              <a href="#">ABOUT</a>
            </li>
          </ul>
        </div>
        <div class="flex items-center gap-6">
          {% if not user.is_authenticated %}
          <ul>
            <li class="hover:bg-gray-200 block py-2 px-3 rounded-md">
              <a href="{% url 'users:sign_in' %}"
                ><svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  class="w-6 h-6"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M15.75 9V5.25A2.25 2.25 0 0 0 13.5 3h-6a2.25 2.25 0 0 0-2.25 2.25v13.5A2.25 2.25 0 0 0 7.5 21h6a2.25 2.25 0 0 0 2.25-2.25V15M12 9l-3 3m0 0 3 3m-3-3h12.75"
                  />
                </svg>
              </a>
            </li>
          </ul>
          {% else %}
          <div class="dropdown">
            <button class="dropbtn">
              <div class="py-2 px-10 duration-700 hover:bg-gray-200 rounded-md">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  class="w-9 h-9"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"
                  />
                </svg>
              </div>
            </button>
            <div class="dropdown-content">
              <a href="{% url 'users:profile' %}">Profile</a>
              <a href="{% url 'memberships:order_list' %}">Order</a>
              {% if user.is_authenticated %}
              <a href="{% url 'users:sign_out_confirmation' %}">Log Out</a>
              {% else %}
              <a href="{% url 'users:sign_in' %}">Log In</a>
              {% endif %}
            </div>
          </div>
          {% endif %}
        </div>
      </nav>
    </header>

    {% block contentBody %}{% endblock %}

    <script src="{% static 'memberships/js/event_priching.js' %}"></script>
    <script>
      const navLinks = document.querySelector(".nav-links");
      function onToggleMenu(e) {
        e.name = e.name === "menu" ? "close" : "menu";
        navLinks.classList.toggle("top-[7%]");
      }
    </script>
    <script src="{% static 'users/js/animation.js' %}"></script>
    <script src="{% static 'users/js/validation.js' %}"></script>
  </body>
</html>

templates/user_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    
   
    {% for message in messages %}
    <div class="bg-gray-100 text-center pt-1 lg:px-4"
      style="position: absolute; top: 0; left: 0; right: 0; z-index: 1000; width: 100%;"
      id="message_alart"
    >
      <div class="p-2 bg-indigo-800 items-center text-indigo-100 leading-none lg:rounded-full flex lg:inline-flex" role="alert">
        <span class="mr-2 p-1 text-left flex-auto">{{ message | safe }}</span>
      </div>
    </div>
    {% endfor %}
    {% block contentBody %}{% endblock %}
    <script src="{% static 'users/js/animation.js' %}"></script>
    <script src="{% static 'users/js/validation.js' %}"></script>
  </body>
</html>