fbo_membership/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("memberships.urls")),
    path("accounts/", include("users.urls")),
    # path("accounts/reset_password/", PasswordResetView.as_view(), name="password_reset"),   
    # path("accounts/reset_password_confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    # path("accounts/reset_password_done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    # path("accounts/reset_password_complete/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

memberships/urls.py
from django.urls import path
from .views.home import HomeView, PlanDetailView, PackageView
from .views.subscriptionPlanView import SubscriptionPlanView
from .views.subscriptionPlanOrder import SubscriptionPlanOrder
from .views.orderListView import OrderListView

app_name = "memberships"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("package/", PackageView.as_view(), name="packageView"),
    path("plans/<slug:slug>/", PlanDetailView.as_view(), name="plan_detail"),
    path("subscription/<slug:membershipPlanSlug>/<slug:packageSlug>/", SubscriptionPlanView.as_view(), name="subscription"),
    path("subscription/order/<slug:membershipPlanSlug>/<slug:packageSlug>/", SubscriptionPlanOrder.as_view(), name="subscription_order"),
    path("orders/", OrderListView.as_view(), name="order_list"),
]

users/urls.py
from django.urls import path
from .views.sign_in import SignInView
from .views.sign_up import SignUpView, ActivateView
from .views.sign_out import SignOutView, SignOutConfirmationView
from .views.profile import ProfileView
from .views.forgot_password import ForgotPasswordView, ResetPasswordView, ResetPasswordEmailDoneView

app_name = "users"

urlpatterns = [
    path("login/", SignInView.as_view(), name="sign_in"),
    path("sign_up/", SignUpView.as_view(), name="sign_up"),
    path('activate/<uidb64>/<token>/', ActivateView.as_view(), name='activate'),
    path("sign_out_confirmation/", SignOutConfirmationView.as_view(), name="sign_out_confirmation"),
    path("sign_out/", SignOutView.as_view(), name="sign_out"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("forgot_password/", ForgotPasswordView.as_view(), name="forgot_password"),
    path("reset_password/<uidb64>/<token>/", ResetPasswordView.as_view(), name="password_reset"),
    path("reset_password_done/", ResetPasswordEmailDoneView.as_view(), name="password_reset_done"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    email = models.EmailField(max_length=254, unique=True, db_index=True)

    def __str__(self):
        return self.email
    
    def get_full_name(self):
        return self.first_name + " " + self.last_name

users/forms/forgot_password_form.py
#forgot password form
from django import forms
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.core.validators import EmailValidator


class ForgotPasswordForm(PasswordResetForm):
    email = forms.CharField(max_length=100, validators=[EmailValidator()], widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'w-full p-2 border border-gray-300 rounded-md'}))

    def clean_email(self):
        email = self.cleaned_data.get("email")
        User = get_user_model()
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("No user found with this email.")
        return email

    
class ResetPasswordForm(forms.Form):
    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(attrs={"class": "w-full p-2 border border-gray-300 rounded-md placeholder:font-light placeholder:text-gray-500"})
    )
    new_password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(attrs={"class": "w-full p-2 border border-gray-300 rounded-md placeholder:font-light placeholder:text-gray-500"})
    )

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get("new_password1")
        new_password2 = cleaned_data.get("new_password2")
        if new_password1 != new_password2:
            raise forms.ValidationError("The passwords do not match.")
        return cleaned_data

users/forms/profile_form.py
from django import forms
from users.models import CustomUser
from django.core.validators import EmailValidator


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Firstname', 'class': 'w-full p-2 border border-gray-300 rounded-md placeholder:font-light'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Lastname', 'class': 'w-full p-2 border border-gray-300 rounded-md placeholder:font-light'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'User Name', 'class': 'w-full p-2 border border-gray-300 rounded-md'}))
    email = forms.CharField(max_length=100, validators=[EmailValidator()], widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'w-full p-2 border border-gray-300 rounded-md', 'readonly': True, 'disabled': True}))
    
    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "username", "email"]
        labels = {
            "first_name": "First Name",
            "last_name": "Last Name",
            "username": "Username",
            "email": "Email",
        }
        

users/forms/sign_in_form.py
#create user sign in form
from django import forms
from users.models import CustomUser
from django.core.exceptions import ValidationError


class SignInForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")

        if not CustomUser.objects.filter(username=username).exists():
            raise ValidationError("User does not exist!")

        user = CustomUser.objects.get(username=username)
        if not user.check_password(password):
            raise ValidationError("Password is incorrect!")

users/forms/sign_up_form.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from users.models import CustomUser

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=100)

    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "username", "email", "password1", "password2"]

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use.")
        return email

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

users/views/forgot_password.py
#forgot password view
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordChangeDoneView
from django.urls import reverse
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.shortcuts import render, redirect
from users.forms.forgot_password_form import ForgotPasswordForm, ResetPasswordForm
from django.contrib import messages


class ForgotPasswordView(PasswordResetView):
    template_name = "users/forgot_password.html"
    form_class = ForgotPasswordForm
    email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    subject_template_name = "users/password_reset_subject.txt"
    token_generator = default_token_generator

    def form_valid(self, form):
        messages.success(self.request, "Password reset email has been sent. Please check your inbox.")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Error submitting password reset request. Please try again.")
        return super().form_invalid(form)
    
class ResetPasswordEmailDoneView(PasswordChangeDoneView):
    template_name = "users/password_reset_done.html"
    


class ResetPasswordView(PasswordResetConfirmView):
    template_name = "users/reset_password.html"
    success_url = reverse_lazy("users:password_reset_done")
    reset_url_token = "password_reset_confirm"
    
    def form_valid(self, form):
        messages.success(self.request, "Password reset successfully.")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Password reset failed. Please try again.")
        return super().form_invalid(form)
 
    

users/views/profile.py
from django.shortcuts import render, redirect
from django.views import View
from users.forms.profile_form import ProfileForm
from users.models import CustomUser
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

@method_decorator(login_required, name='dispatch')
class ProfileView(View):
    def get(self, request):
        user = request.user
        form = ProfileForm(instance=user)
        return render(request, "users/profile.html", {"form": form})

    def post(self, request):
        user = request.user
        form = ProfileForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "Profile updated successfully!")
            return redirect("users:profile")
        else:
            messages.error(request, "There was an error updating your profile.")
        return render(request, "users/profile.html", {"form": form})

users/views/sign_in.py
# create user sign in view class based view
from django.shortcuts import render, redirect
from django.views import View
from users.forms.sign_in_form import SignInForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from users.helper import is_safe_url




class SignInView(View):
    def get(self, request):
        form = SignInForm()
        return render(request, "users/sign_in.html", {"form": form})
    
    

    def post(self, request):
        form = SignInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "User logged in successfully!")
                next_url = request.POST.get('next') 
                if next_url:
                    if is_safe_url(next_url, request.get_host()):
                        return redirect(next_url)
                    else:
                        return redirect("memberships:home")
                else:
                    return redirect("memberships:home")
        return render(request, "users/sign_in.html", {"form": form})

users/views/sign_out.py
# create sinout confirmation view and signout view
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib import messages

# set login required 
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

@method_decorator(login_required, name='dispatch')
class SignOutConfirmationView(TemplateView):
    template_name = "users/sign_out_confirmation.html"

    def get(self, request):
        return render(request, self.template_name)
    
    
@method_decorator(login_required, name='dispatch')
class SignOutView(TemplateView):
    def post(self, request):
        logout(request)
        messages.success(request, "User logged out successfully!")
        return redirect("users:sign_in")

users/views/sign_up.py
from users.forms.sign_up_form import SignUpForm
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from users.helper import activateEmail
from django.contrib.auth import get_user_model
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str
from users.tokens import account_activation_token




class SignUpView(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, "users/sign_up.html", {"form": form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activateEmail(request, user, form.cleaned_data.get("email"))
            return redirect("users:sign_in")
        return render(request, "users/sign_up.html", {"form": form})

class ActivateView(View):
    def get(self, request, uidb64, token):
        User = get_user_model()
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except Exception as e:
            user = None
        
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, "Account activated successfully.")
            return redirect("users:sign_in")
        else:
            messages.error(request, "Activation link is invalid.")
            return redirect("users:sign_in")

templates/users/activate_account.html
{% autoescape off %}

Hi {{ user.username }},
Please click the link below to confirm your registration:
http://{{domain}}{% url 'users:activate' uidb64=uid token=token %}

{% endautoescape %}

templates/users/forgot_password.html
{% extends "memberships_base.html" %} {% load static %} {% block title %}Forgot
Password{% endblock %} {% block contentBody %}
<div class="flex items-center justify-center min-h-screen bg-gray-100">
  <div
    class="relative flex flex-col m-6 space-y-8 bg-white shadow-2xl rounded-2xl md:flex-row md:space-y-0"
  >
    <!-- left side  -->
    <div class="relative">
      <img
        src="https://images.pexels.com/photos/2246476/pexels-photo-2246476.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        alt="img"
        class="w-[400px] h-full hidden rounded-l-2xl md:block object-cover"
      />
    </div>
    <!-- right side -->
    <div class="flex flex-col justify-center p-8 md:p-14">
      <span class="mb-3 text-3xl font-bold">Forgot Password</span>
      <span class="font-light text-gray-400 mb-8">
        Enter your email address to reset your password.
      </span>
      <form
        action="{% url 'users:forgot_password' %}"
        method="POST"
        id="forgotPasswordForm"
      >
        {% csrf_token %}
        <div class="mt-1">
        {{ form }}
        </div>

        <button
          class="w-full bg-black text-white p-2 rounded-lg mb-6 hover:bg-white hover:text-black font-semibold hover:border hover:border-gray-300 mt-4 duration-300"
          submit
        >
          Submit
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/users/password_reset_done.html
{% extends "memberships_base.html" %} {% load static %} {% block title %}
Password Reset Email Sent Successfully {% endblock %} 
{% block contentBody %}
<div class="flex items-center justify-center min-h-screen bg-gray-100">
  <div
    class="relative flex flex-col m-6 space-y-8 bg-white shadow-2xl rounded-2xl md:flex-row md:space-y-0"
  >
    <!-- right side -->
    <div class="flex flex-col justify-center p-8 md:p-14">
      <span class="mb-3 text-3xl font-bold">
        Password Reset Email Sent Successfully
      </span>
      <span class="font-light text-gray-400 mb-8">
        Please check your email for the password reset link. If you don't see it
        in your inbox, check your spam folder. If you still can't find it,
        please contact us at
      </span>
      <a href="{% url 'memberships:home' %}">
        <button
          class="w-100 bg-black text-white p-2 rounded-lg mb-6 hover:bg-white hover:text-black font-semibold hover:border hover:border-gray-300 duration-300"
        >
          Return Home
        </button>
      </a>
    </div>
  </div>
</div>
{% endblock %}

templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}
	
{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}
	
{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/users/profile.html
{% extends "memberships_base.html" %} {% load static %} {% block title %} {{
user.username }} Profile {% endblock %} {% block contentBody %}
<div class="flex items-center justify-center min-h-screen bg-gray-100">
  <div
    class="relative flex flex-col m-6 space-y-8 bg-white shadow-2xl rounded-2xl md:flex-row md:space-y-0"
  >
    <div class="flex flex-col justify-center p-8 md:p-14">
      <h3 class="mb-3 text-4xl font-bold text-center">Profile</h3>
      <span class="font-light text-gray-400 mb-8">
        You can update your profile information here.
      </span>

      <div class=" ">
        <form action="{% url 'users:profile' %}" method="POST" id="profileForm">
          {% csrf_token %} {{ form.as_p }}
          <div class="mt-5">
            <a href="#">
              <button
                class="w-full bg-black text-white p-2 rounded-lg mb-6 hover:bg-white hover:text-black hover:border hover:border-gray-300 duration-500 font-bold"
              >
                Save
              </button>
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/users/sign_in.html
{% extends "memberships_base.html" %}
{% load static %}
{% block title %}Sign In{% endblock %}
{% block contentBody %}

    <div class="flex items-center justify-center min-h-screen bg-gray-100">
      <div
        class="relative flex flex-col m-6 space-y-8 bg-white shadow-2xl rounded-2xl md:flex-row md:space-y-0"
      >
        <!-- left side  -->
        <div class="relative">
          <img
            src="https://images.pexels.com/photos/2246476/pexels-photo-2246476.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
            alt="img"
            class="w-[400px] h-full hidden rounded-l-2xl md:block object-cover"
          />
        </div>
        <!-- right side -->
        <div class="flex flex-col justify-center p-8 md:p-14">
          <span class="mb-3 text-4xl font-bold">Welcome FBO</span>
          <span class="font-light text-gray-400 mb-8">
            FBO offers membership packages as a simple and <br />cost effective
            way to access a wide range of facilities.
          </span>
          {% if form.errors.items %}
            <div
                class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative"
                role="alert"
            >
            <div class="flex">
                <div class="py-1">
                    <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
                </div>
                <div>
                    {% for field, errors in form.errors.items %} 
                        {% for error in errors %}
                        <span class="block sm:inline">{{error}}</span>
                        {% endfor %} 
                    {% endfor %}
                </div>
            </div>
            </div>
          {% endif %}

          <form
            action="{% url 'users:sign_in' %}"
            method="POST"
            id="signInForm"
          >
            {% csrf_token %}
            <div class="py-4">
              <span class="mb-2 text-md">Username</span>
              <input
                type="text"
                class="w-full p-2 border border-gray-300 rounded-md placeholder:font-light placeholder:text-gray-500"
                name="username"
                autofocus
                placeholder="Username"
                id="userName"
              />
              <!-- error message -->
              <div class="text-red-500">
                <span class="text-red-500 text-xs" id="userNameError"> </span>
              </div>
            </div>
            <div class=" ">
              <span class="mb-2 text-md">Password</span>
              <input
                type="password"
                class="w-full p-2 border border-gray-300 rounded-md placeholder:font-light placeholder:text-gray-500"
                name="password"
                placeholder="Password"
                id="password"
                
              />
              <!-- error message -->
              <div class="text-red-500">
                <span class="text-red-500 text-xs" id="passwordError"> </span>
              </div>
            </div>
            <button
              class="w-full bg-black text-white p-2 rounded-lg my-6 hover:bg-white hover:text-black hover:border hover:border-gray-300"
              type="submit"
              id="submitBtn"
            >
              Sign in
            </button>
          </form>
          <div class="flex justify-center w-full py-4">
            <a href="{% url 'users:forgot_password' %}" class="font-bold text-md"
              >Forgot password</a
            >
          </div>
          <div class="text-center text-gray-400">
            Dont'have an account?
            <a href="{% url 'users:sign_up' %}" class="font-bold text-black"
              >Sign up for free</a
            >
          </div>
        </div>
      </div>
    </div>
    {% endblock %}

templates/users/sign_out_confirmation.html
{% extends "memberships_base.html" %} 
{% load static %} 
{% block title %}Sign Out Confirm{% endblock %} 
{% block contentBody %}
<div class="flex items-center justify-center min-h-full bg-gray-100">
  <div
    class="relative flex flex-col  space-y-8 bg-white shadow-2xl rounded-2xl md:flex-row md:space-y-0"
  >
    <!-- right side -->
    <div class="flex flex-col justify-center p-8 md:p-14">
      <span class="mb-3 text-3xl font-bold md:text-4xl">
        Are you sure you want to sign out? 
      </span>
      <span class="font-light text-gray-400 mb-8">
        You can always sign in again if you want to access your account.
      </span>
      <form action="{% url 'users:sign_out' %}" method="POST">
        {% csrf_token %}
        <div class="flex justify-center">
          <button
            type="submit"
            class="px-4 py-2 mx-5 text-white bg-red-500 rounded-md hover:bg-red-600"
          >
            Sign Out
          </button>
          <a
            href="{% url 'memberships:home' %}"
            class="px-4 py-2 mx-5 text-white bg-blue-500 rounded-md hover:bg-blue-600"
          >
            Cancel
          </a>
        </div>
    </div>
  </div>
</div>
{% endblock %}

templates/users/sign_up.html
{% extends "user_base.html" %} 
{% load static %} 
{% block title %}Sign Up{% endblock %} 
{% block contentBody %}
<div class="flex items-center justify-center min-h-screen bg-gray-100">
  <div
    class="relative flex flex-col m-6 space-y-8 bg-white shadow-2xl rounded-2xl md:flex-row md:space-y-0"
  >
    <!-- left side  -->
    <div class="relative">
      <img
        src="https://images.pexels.com/photos/2246476/pexels-photo-2246476.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        alt="img"
        class="w-[400px] h-full hidden rounded-l-2xl md:block object-cover"
      />
    </div>
    <!-- left side -->
    <div class="flex flex-col justify-center p-8 md:p-14">
      <span class="mb-3 text-4xl font-bold">Register</span>
      <span class="font-light text-gray-400">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      </span>
      {% if form.errors.items %}
            <div
                class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative"
                role="alert"
            >
                <div class="flex">
                    <div class="py-1">
                        <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
                    </div>
                    <div>
                        {% for field, errors in form.errors.items %} 
                            {% for error in errors %}
                            <span class="block sm:inline">{{error}}</span>
                            {% endfor %} 
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
      <!-- right side -->

      <div class=" ">
        <form action="{% url 'users:sign_up' %}"
            method="POST"
            id="signUpForm"
        >
            {% csrf_token %}
          <div class="grid grid-cols-2 gap-5 mt-5">
            <div>
              <span class="mb-2 text-md">First Name</span>
              <input
                type="text"
                class="w-full p-2 border border-gray-300 rounded-md placeholder:font-light"
                autofocus
                placeholder="First Name"
                id="firstName"
                name="first_name"
                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
              />
              <div class="text-red-500">
                <span class="text-red-500 text-xs" id="firstNameError"> </span>
              </div>
            </div>
            <div>
              <span class="mb-2 text-md">Last Name</span>
              <input
                type="text"
                class="w-full p-2 border border-gray-300 rounded-md placeholder:font-light"
                placeholder="Last Name"
                id="lastName"
                name="last_name"
                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
              />
              <div class="text-red-500">
                <span class="text-red-500 text-xs" id="lastNameError"> </span>
              </div>
            </div>
          </div>
          <div class="grid grid-cols-2 gap-5 mt-5">
            <div>
                <span class="mb-2 text-md">Username</span>
                <input
                type="text"
                class="w-full p-2 border border-gray-300 rounded-md placeholder:font-light"
                placeholder="Username"
                id="userName"
                name="username"
                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                />
                <div class="text-red-500">
                    <span class="text-red-500 text-xs" id="userNameError"> </span>
                  </div>
            </div>
            <div>
                <span class="mb-2 text-md">Email</span>
                <input
                type="text"
                class="w-full p-2 border border-gray-300 rounded-md placeholder:font-light"
                placeholder="Email"
                id="email"
                name="email"
                value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                />
                <div class="text-red-500">
                    <span class="text-red-500 text-xs" id="emailError"> </span>
                  </div>
            </div>
          </div>
          <div class="mt-5">
            <span class="mb-2 text-md">Password</span>
            <input
              type="password"
              class="w-full p-2 border border-gray-300 rounded-md"
              placeholder="Password"
                id="password"
                name="password1"
            />
            <div class="text-red-500">
                <span class="text-red-500 text-xs" id="passwordError"> </span>
              </div>
          </div>
          <div class="mt-5">
            <span class="mb-2 text-md">Confirm Password</span>
            <input
              type="password"
              class="w-full p-2 border border-gray-300 rounded-md"
              placeholder="Confirm Password"
                id="confirmPassword"
                name="password2"
            />
            <div class="text-red-500">
                <span class="text-red-500 text-xs" id="confirmPasswordError"> </span>
              </div>
          </div>
          <div class="mt-5">
            <input 
            type="checkbox" 
            class="border border-gray-400" 
            id="terms"
            />
            <span>
              I accept the
              <a href="#" class="text-purple-500 font-semibold">Terms of Use</a>
              &
              <a href="#" class="text-purple-500 font-semibold"
                >Privacy Policy</a
              >
            </span>
          </div>
          <div class="mt-5">
            <button
              class="w-full bg-black text-white p-2 rounded-lg mb-6 hover:bg-white hover:text-black hover:border hover:border-gray-300"
                type="submit"
                id="submitBtn"
            >
              Sign Up
            </button>
          </div>
          <div class="text-center text-gray-400">
            Already have an account?
            <a href="{% url 'users:sign_in' %}" class="font-bold text-black">
                Sign In 
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}