fbo_membership/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("memberships.urls")),
    path("accounts/", include("users.urls")),
    # path("accounts/reset_password/", PasswordResetView.as_view(), name="password_reset"),   
    # path("accounts/reset_password_confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    # path("accounts/reset_password_done/", PasswordResetDoneView.as_view(), name="password_reset_done"),
    # path("accounts/reset_password_complete/", PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

memberships/urls.py
from django.urls import path
from .views.home import HomeView, PlanDetailView, PackageView
from .views.subscriptionPlanView import SubscriptionPlanView
from .views.subscriptionPlanOrder import SubscriptionPlanOrder
from .views.orderListView import OrderListView

app_name = "memberships"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("package/", PackageView.as_view(), name="packageView"),
    path("plans/<slug:slug>/", PlanDetailView.as_view(), name="plan_detail"),
    path("subscription/<slug:membershipPlanSlug>/<slug:packageSlug>/", SubscriptionPlanView.as_view(), name="subscription"),
    path("subscription/order/<slug:membershipPlanSlug>/<slug:packageSlug>/", SubscriptionPlanOrder.as_view(), name="subscription_order"),
    path("orders/", OrderListView.as_view(), name="order_list"),
]

users/urls.py
from django.urls import path
from .views.sign_in import SignInView
from .views.sign_up import SignUpView, ActivateView
from .views.sign_out import SignOutView, SignOutConfirmationView
from .views.profile import ProfileView
from .views.forgot_password import ForgotPasswordView, ResetPasswordView, ResetPasswordEmailDoneView

app_name = "users"

urlpatterns = [
    path("login/", SignInView.as_view(), name="sign_in"),
    path("sign_up/", SignUpView.as_view(), name="sign_up"),
    path('activate/<uidb64>/<token>/', ActivateView.as_view(), name='activate'),
    path("sign_out_confirmation/", SignOutConfirmationView.as_view(), name="sign_out_confirmation"),
    path("sign_out/", SignOutView.as_view(), name="sign_out"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("forgot_password/", ForgotPasswordView.as_view(), name="forgot_password"),
    path("reset_password/<uidb64>/<token>/", ResetPasswordView.as_view(), name="password_reset"),
    path("reset_password_done/", ResetPasswordEmailDoneView.as_view(), name="password_reset_done"),
]

memberships/models.py
from typing import Iterable, List
from django.db import models
from users.models import CustomUser
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from datetime import timedelta
import hashlib
import secrets

class MembershipServices(models.Model):
    name: str = models.CharField(max_length=100, db_index=True)
    slug: str = models.SlugField(max_length=100, db_index=True, unique=True)
    description: str = models.TextField(null=True, blank=True)
    created_at: str = models.DateTimeField(auto_now_add=True)
    updated_at: str = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Membership Service"
        verbose_name_plural = "Membership Services"
        ordering = ["id"]

    # slug auto generation
    def save(self, *args, **kwargs) -> None:
        self.slug: str = self.slug or slugify(self.name)
        super().save(*args, **kwargs)


class MembershipPlans(models.Model):
    name: str = models.CharField(max_length=100, db_index=True)
    slug: str = models.SlugField(max_length=100, db_index=True, unique=True)
    description: str = models.TextField(null=True, blank=True)
    price: float = models.FloatField(default=0.0)
    access_to_services: Iterable[MembershipServices] = models.ManyToManyField(
        MembershipServices
    )
    created_at: str = models.DateTimeField(auto_now_add=True)
    updated_at: str = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs) -> None:
        self.slug: str = self.slug or slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name: str = "Membership Plan"
        verbose_name_plural: str = "Membership Plans"
        ordering: List[str] = ["created_at"]


class Pricing(models.Model):
    PACKAGE_OPTIONS = (
        ("Monthly", _("Monthly")),
        ("Quarterly", _("Quarterly")),
        ("Half Yearly", _("Half Yearly")),
        ("Yearly", _("Yearly")),
    )
    membership_plan: Iterable[MembershipPlans] = models.ForeignKey(
        MembershipPlans, on_delete=models.CASCADE, verbose_name="Membership Plan"
    )
    package: str = models.CharField(
        max_length=20,
        choices=PACKAGE_OPTIONS,
        default="monthly",
        verbose_name="Package",
    )
    slug: str = models.SlugField(max_length=100, db_index=True, unique=True, default="")
    discerption: str = models.TextField(null=True, blank=True)
    days: int = models.IntegerField(default=30, verbose_name="Days")
    price: float = models.FloatField(default=0.0, verbose_name="Price")
    created_at: str = models.DateTimeField(auto_now_add=True)
    updated_at: str = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.membership_plan} - {self.package} - {self.price}"
    
    def save(self, *args, **kwargs) -> None:
        self.slug: str = slugify(self.membership_plan.name + self.package)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name: str = "Pricing"
        verbose_name_plural: str = "Pricings"
        ordering: List[str] = ["created_at"]


class SubscriptionPlan(models.Model):
    subscription_id = models.CharField(max_length=10, unique=True, null=True, blank=True)
    membership_plan = models.ForeignKey(MembershipPlans, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    pricing = models.ForeignKey(Pricing, on_delete=models.CASCADE, null=True, blank=True)
    number_of_people = models.IntegerField(verbose_name="Number of People", default=1)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # generate unique subscription id and check uniqueness or regenerate
    def generate_unique_id(self):
        while True:
            subscription_id = secrets.token_urlsafe(5)
            if not SubscriptionPlan.objects.filter(subscription_id=subscription_id).exists():
                return subscription_id
                

    
    
    def __str__(self):
        return f"{self.user} - {self.membership_plan}"
    

    def save(self, *args, **kwargs):
        if not self.subscription_id:
            self.subscription_id = self.generate_unique_id()
        if self.pricing and not self.end_date and self.start_date:
            self.end_date = self.start_date + timedelta(days=int(self.pricing.days))
        super().save(*args, **kwargs)

memberships/views/home.py
# class base home view
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect
from memberships.models import MembershipPlans, MembershipServices, Pricing




class HomeView(ListView):
    template_name = "memberships/home.html"
    model = MembershipPlans
    context_object_name = "membershipPlans"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        membershipServices = MembershipServices.objects.all()
        context["title"] = "Home"
        context["membershipServices"] = membershipServices
        return context


class PlanDetailView(DetailView):
    template_name = "memberships/plan_detail.html"
    model = MembershipPlans
    context_object_name = "membershipPlan"
    slug_field = "slug"
    slug_url_kwarg = "slug"
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pricings = Pricing.objects.filter(membership_plan=self.object)
        context["title"] = "Plan Detail"
        context["pricings"] = pricings
        return context


class PackageView(ListView):
    template_name = "memberships/PACKAGE.html"
    model = MembershipPlans
    context_object_name = "membershipPlans"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        membershipServices = MembershipServices.objects.all()
        context["title"] = "Home"
        context["membershipServices"] = membershipServices
        return context

memberships/views/orderListView.py
from memberships.models import SubscriptionPlan, MembershipPlans, Pricing
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from datetime import timedelta, datetime


class OrderListView(ListView):
    model = SubscriptionPlan
    template_name = "memberships/order_list.html"
    context_object_name = "orders"

    @method_decorator(login_required)
    def get(self, request: HttpRequest) -> HttpResponse:
        orders = SubscriptionPlan.objects.filter(user=request.user).order_by("-id")
        return render(request, self.template_name, {self.context_object_name: orders})

memberships/views/subscriptionPlanOrder.py
from memberships.models import SubscriptionPlan, MembershipPlans, Pricing
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import CreateView
from datetime import timedelta, datetime



@method_decorator(login_required, name='dispatch')
class SubscriptionPlanOrder(CreateView):
    model = SubscriptionPlan
    fields = ["membership_plan", "user", "pricing"]
    
    
    def post(self, request: HttpRequest, membershipPlanSlug: str, packageSlug: str) -> HttpResponse:
        try:
            membershipPlan = MembershipPlans.objects.get(slug=membershipPlanSlug)
            package = Pricing.objects.get(slug=packageSlug)
            date_str = request.POST.get("booking_date")
            number_of_people = request.POST.get("number_of_people")
            date_format = "%m/%d/%Y"
            start_date = datetime.strptime(date_str, date_format)
            end_date = start_date + timedelta(days=package.days)
            SubscriptionPlan.objects.create(
                membership_plan=membershipPlan,
                user=request.user,
                pricing=package,
                number_of_people = number_of_people,
                start_date = start_date,
                end_date = end_date
                
            )
            messages.success(request, "Subscription Plan created successfully")
        except MembershipPlans.DoesNotExist:
            messages.error(request, "Membership plan not found.")
        except Pricing.DoesNotExist:
            messages.error(request, "Pricing package not found.")
        
        return redirect(reverse_lazy("memberships:order_list"))

memberships/views/subscriptionPlanView.py
from django.http import HttpRequest, HttpResponse
from memberships.models import MembershipPlans, MembershipServices, Pricing, SubscriptionPlan
from django.views.generic import CreateView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
class SubscriptionPlanView(CreateView):
    # model = SubscriptionPlan
    # fields = ["membership_plan", "user", "pricing"]
    
    
    def get(self, request: HttpRequest, membershipPlanSlug: str, packageSlug: str) -> HttpResponse:
        membershipPlan = MembershipPlans.objects.get(slug=membershipPlanSlug)
        package = Pricing.objects.get(slug=packageSlug)
        SubscriptionPlan.objects.create(
            membership_plan=membershipPlan,
            user=request.user,
            pricing=package,
        )
        messages.success(request, "Subscription Plan created successfully")
        return redirect(reverse_lazy("memberships:home"))

templates/memberships/PACKAGE.html
{% extends "memberships_base.html" %} {% block title %}FIRST BRIDGEFORD OFFICES
FORMS FOR BAHIJ{% endblock %} {% block contentBody %}
<div class="min-h-screen flex justify-center items-center pt-8">
    <div class="max-w-screen-xl w-full">
        <div class="text-center font-semibold">
            <h1 class="text-3xl">
                <span class="text-blue-700 tracking-wide">MEMBERSHIP</span>
                <span>Plans</span>
            </h1>
            <p class="pt-6 text-xl text-gray-400 font-normal w-full px-8 md:w-full">
                FBO offers membership packages as a simple and cost-effective way to access a wide range of
                facilities.
            </p>
        </div>

        <!-- Pricing Cards -->
        <div class=" grid grid-cols-1 lg:grid-cols-4 md:grid-cols-2 md:gap-8 gap-4 mt-12 ml-4 mr-4">
            <!-- Gold Card -->
            {% for membership in membershipPlans %}
            <div class="bg-white text-center rounded-3xl shadow-xl p-8">
                <h1 class="text-black font-semibold text-xl"><i class="fas fa-star" style="color: gold;"></i> {{ membership.name|upper }} </h1>
                <p class="pt-2 tracking-wide">
                    <span class="text-gray-400 align-top">$ </span>
                    <span class="text-3xl font-semibold">
                        {{ membership.price }}
                    </span>
                    <span class="text-gray-400 font-medium">/ month</span>
                </p>
                <hr class="mt-4 border-1">
                <div class="pt-8">
                    {% for service in membershipServices %}
                    {% if service not in membership.access_to_services.all %}
                    <p class="font-semibold text-black text-left pt-5">
                        <i class="fa-solid fa-xmark text-red-600"></i>
                        <span class="pl-1">
                            {{ service.name }}
                        </span>
                    </p>
                    {% else %}
                    <p class="font-semibold text-black text-left pt-5">
                        <i class="fa-solid fa-check text-green-600"></i>
                        <span class="pl-1">
                            {{ service.name }}
                        </span>
                    </p>
                    {% endif %}
                    {% endfor %}
                    
                </div>
                <a href="{% url 'memberships:plan_detail' slug=membership.slug %}"  class="block w-full py-2 bg-blue-600 mt-8 rounded-xl text-white font-medium">Learn More <i class="fa-solid fa-arrow-right"></i></a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/memberships/home.html
{% extends "memberships_base.html" %} {% block title %}FIRST BRIDGEFORD OFFICES
FORMS FOR BAHIJ{% endblock %} {% block contentBody %}
<div class="min-h-screen flex justify-center items-center pt-8">
    <div class="max-w-screen-xl w-full">
        <div class="text-center font-semibold">
            <h1 class="text-3xl">
                <span class="text-blue-700 tracking-wide">MEMBERSHIP</span>
                <span>Plans</span>
            </h1>
            <p class="pt-6 text-xl text-gray-400 font-normal w-full px-8 md:w-full">
                FBO offers membership packages as a simple and cost-effective way to access a wide range of
                facilities.
            </p>
        </div>

        <!-- Pricing Cards -->
        <div class=" grid grid-cols-1 lg:grid-cols-4 md:grid-cols-2 md:gap-8 gap-4 mt-12 ml-4 mr-4">
            <!-- Gold Card -->
            {% for membership in membershipPlans %}
            <div class="bg-white text-center rounded-3xl shadow-xl p-8">
                <h1 class="text-black font-semibold text-xl"><i class="fas fa-star" style="color: gold;"></i> {{ membership.name|upper }} </h1>
                <p class="pt-2 tracking-wide">
                    <span class="text-gray-400 align-top">$ </span>
                    <span class="text-3xl font-semibold">
                        {{ membership.price }}
                    </span>
                    <span class="text-gray-400 font-medium">/ month</span>
                </p>
                <hr class="mt-4 border-1">
                <div class="pt-8">
                    {% for service in membershipServices %}
                    {% if service not in membership.access_to_services.all %}
                    <p class="font-semibold text-black text-left pt-5">
                        <i class="fa-solid fa-xmark text-red-600"></i>
                        <span class="pl-1">
                            {{ service.name }}
                        </span>
                    </p>
                    {% else %}
                    <p class="font-semibold text-black text-left pt-5">
                        <i class="fa-solid fa-check text-green-600"></i>
                        <span class="pl-1">
                            {{ service.name }}
                        </span>
                    </p>
                    {% endif %}
                    {% endfor %}
                    
                </div>
                <a href="{% url 'memberships:plan_detail' slug=membership.slug %}"  class="block w-full py-2 bg-blue-600 mt-8 rounded-xl text-white font-medium">Learn More <i class="fa-solid fa-arrow-right"></i></a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/memberships/order_list.html
{% extends "memberships_base.html" %} {% block title %}
Order List | {{ user.username }}
{% endblock %} {% block contentBody %}

<div class="min-h-screen flex justify-center items-center pt-0">
    <div class="max-w-screen-xl w-full">
        <div class="text-center font-semibold">
            <h1 class="text-3xl">
                <span class="text-blue-700 tracking-wide">ORDER</span>
                <span>List</span>
            </h1>
            <p class="pt-6 text-xl text-gray-400 font-normal w-full px-8 md:w-full">
                Here is the list of all your orders.
            </p>
        </div>

        <!-- Order List -->
        <div class=" grid grid cols-1 lg:grid-cols-4 md:grid-cols-2 md:gap-8 gap-4 mt-12 ml-4 mr-4">
            <!-- Order Card -->
            {% for order in orders %}
            <div class="bg-white text-center rounded-3xl shadow-xl p-8">
                <h1 class="text-black font-semibold text-xl"><i class="fas fa-star" style="color: gold;"></i> {{ order.membership_plan.name|upper }} </h1>   
                <p class="pt-2 tracking-wide">
                    <span class="text-gray-400 align-top">$ </span>
                    <span class="text-3xl font-semibold">
                        {{ order.pricing.price }}
                    </span>
                    <span class="text-gray-400 font-medium">/ {{ order.pricing.package }}</span>
                </p>
                <hr class="mt-4 border-1">
                <div class="pt-8">
                    <p class="font-semibold text-black text-left">
                        <i class="fa-solid fa-id-card text-blue-600"></i>
                        <span class="pl-1">
                            {{ order.subscription_id }}
                        </span>
                    </p>
                    <p class="font-semibold text-black text-left pt-5">
                        <i class="fa-solid fa-calendar text-blue-600"></i>
                        <span class="pl-1">
                            {{ order.start_date }}
                        </span>
                    </p>
                    <p class="font-semibold text-black text-left pt-5">
                        <i class="fa-solid fa-calendar text-blue-600"></i>
                        <span class="pl-1">
                            {{ order.end_date }}
                        </span>
                    </p>
                    {% if order.active == True %}
                    <p class="font-semibold text-black text-left pt-5">
                        <i class="fa-solid fa-check text-green-600"></i>
                        <span class="pl-1">
                            Active
                        </span>
                    </p>
                    {% else %}
                    <p class="font-semibold text-black text-left pt-5">
                        <i class="fa-solid fa-times text-red-600"></i>
                        <span class="pl-1">
                            Inactive
                        </span>
                    </p>
                    {% endif %}
                </div>
                <!-- <a href=""  class="block w-full py-2 bg-blue-600 mt-8 rounded-xl text-white font-medium">View Order <i class="fa-solid fa-arrow-right"></i></a> -->
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/memberships/plan_detail.html
{% extends "memberships_base.html" %} {% block title %}
{{membershipPlan.name|upper }} {% endblock %} {% block contentBody %}
<section class="h-screen py-12 bg-gray-100">
  <div class="max-w-5xl mx-auto sm:px-6 lg:px-8">
    <!-- Pricing Card -->
    <div class="bg-white shadow-lg rounded-lg md:flex border-1">
      <div class="px-6 py-8">
        <h3 class="text-lg font-semibold text-gray-900 mb-4">
          Choose a pricing plan:
        </h3>
        <ul class="md:flex grid grid-cols-2">
          {% for pricing in pricings %} {% if forloop.counter == 1 %}
          <li class="mb-px">
            <button
              onclick="changePrice( '{{ pricing.price }}', '{{ pricing.package }}', `{{ pricing.discerption }}`, '{{ pricing.slug }}', '{{ membershipPlan.slug}}')"
              id="{{pricing.slug}}"
              class="w-full h-16 md:py-5 px-8 bg-white border border-gray-300 md:rounded-l-lg font-semibold text-gray-800 hover:bg-gray-300 btns"
            >
              {{ pricing.package }}
            </button>
          </li>
          {% elif forloop.counter == 4 %}
          <li class="mb-px">
            <button
              onclick="changePrice( '{{ pricing.price }}', '{{ pricing.package }}', `{{ pricing.discerption }}`, '{{ pricing.slug }}', '{{ membershipPlan.slug}}')"
              id="{{pricing.slug}}"
              class="w-full h-16 py-2 px-8 bg-white border border-gray-300 md:rounded-r-lg font-semibold text-gray-800 hover:bg-gray-300 btns"
            >
              {{ pricing.package }}
            </button>
          </li>
          {% else %}
          <li class="mb-px">
            <button
              onclick="changePrice( '{{ pricing.price }}', '{{ pricing.package }}', `{{ pricing.discerption }}`, '{{ pricing.slug }}', '{{ membershipPlan.slug}}')"
              id="{{pricing.slug}}"
              class="w-full h-16 px-8 bg-white border border-gray-300 font-semibold text-gray-800 hover:bg-gray-300 btns"
            >
              {{ pricing.package }}
            </button>
          </li>
          {% endif %} {% endfor %}
        </ul>

        <!-- Pricing Details -->
        <div class="mt-8 md:w-full">
          <div class="text-lg font-semibold mb-2">
            {{ membershipPlan.name }} details:
          </div>
          <p class="text-gray-700" id="membership_discerption">
            {{ membershipPlan.description }}
          </p>
        </div>
      </div>

      <!-- Second Section -->
      <div class="bg-white rounded-lg md:w-full p-8">
          <form method="POST"
            id="membership_form"
          >
            {% csrf_token %}
          <div class="text-2xl font-bold text-gray-900 mb-6">
            {{ membershipPlan.name }} Plan
          </div>
          <div class="flex justify-between pb-5">
            <div class="relative z-0 w-full mb-5 group">
              <label class="block text-gray-700 text-sm font-bold mb-2"
                >Number of people:</label
              >
              <div
                class="py-2 px-3 inline-block bg-white border border-gray-200 rounded-lg"
              >
                <div class="flex items-center gap-x-1.5">
                  <button
                    type="button"
                    id="decrement"
                    class="size-6 inline-flex justify-center items-center gap-x-2 text-sm font-medium rounded-md border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none"
                    data-hs-input-number-decrement=""
                  >
                    <svg
                      class="flex-shrink-0 size-3.5"
                      xmlns="http://www.w3.org/2000/svg"
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    >
                      <path d="M5 12h14"></path>
                    </svg>
                  </button>
                  <input
                    id="quantity"
                    name="number_of_people"
                    class="p-0 w-6 bg-transparent border-0 text-gray-800 text-center focus:ring-0"
                    type="text"
                    value="1"
                  />
                  <button
                    type="button"
                    id="increment"
                    class="size-6 inline-flex justify-center items-center gap-x-2 text-sm font-medium rounded-md border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none"
                    data-hs-input-number-increment=""
                  >
                    <svg
                      class="flex-shrink-0 size-3.5"
                      xmlns="http://www.w3.org/2000/svg"
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                      stroke-linejoin="round"
                    >
                      <path d="M5 12h14"></path>
                      <path d="M12 5v14"></path>
                    </svg>
                  </button>
                </div>
              </div>
            </div>
            <div class="relative z-0 w-full mb-5 group">
              <label class="block text-gray-700 text-sm font-bold mb-2"
                >Booking Date:</label
              >
              <div class="relative max-w-sm">
                <div
                  class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none"
                >
                  <svg
                    class="w-4 h-4 text-gray-500"
                    aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"
                    />
                  </svg>
                </div>
                <input
                  datepicker
                  type="text"
                  id="booking_date"
                  name="booking_date"
                  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5"
                  placeholder="Select date"
                  onblur="checkDate()"
                />
              </div>
              <span id="dateError" class="text-red-500"
                ></span
              >
            </div>
          </div>

          <div
            class="text-3xl font-semibold text-gray-900"
            id="membership_price"
          >
            ${{ membershipPlan.price }} / Monthly
          </div>
          <button
            id="buy_now"
            class="block w-full py-2 px-4 mt-5 bg-blue-600 text-white font-bold rounded-md text-center hover:bg-blue-700 focus:ring-2 mb-4"
          >
            Buy now
          </button>
          </form>
        </div>
    </div>
  </div>
</section>

{% endblock %}